// Code generated by fes (devel). DO NOT EDIT.
package schema

import "fmt"

type compositionID uint64

const (
	compositionIDFoo compositionID = iota
	compositionIDBar
	compositionIDFooBar
)

var (
	zeroFoo Foo
	zeroBar Bar
)

type entityKey struct {
	composition compositionID
	index       int
}

// ///////////////////////////////////////
// ///////////////////////////////////////
// Foos
// ///////////////////////////////////////
// ///////////////////////////////////////
type FooResult struct {
	IDs  []int
	Foos []Foo
}

type FooAccessor struct {
	current   int
	ids       []*[]int
	slicesFoo []*[]Foo
}

func (a *FooAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *FooAccessor) Foos() FooResult {
	return FooResult{
		IDs:  *a.ids[a.current],
		Foos: *a.slicesFoo[a.current],
	}
}

type FooStore interface {
	Put(foo Foo) (id int)
	ByID(id int) (foo Foo)
	All() FooAccessor
	Delete(id int)
}

func newStore_Foo(keys *[]*entityKey, foobar *store_foobar) *store_foo {
	store := &store_foo{
		keys: keys,
		typeMap: []*int{
			new(0), // compositionIDFoo,
			nil,    // compositionIDBar,
			new(1), // compositiionIDFooBar
		},
	}

	store.delFns = []func(int){
		store.deleteNative,  // compositionIDFoo
		nil,                 // compositionIDBar
		foobar.deleteNative, // compositionIDFooBar
	}

	return store
}

type store_foo struct {
	keys    *[]*entityKey
	typeMap []*int
	delFns  []func(int)
	ids     []*[]int
	foos    []*[]Foo
}

func (s *store_foo) Put(foo Foo) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionIDFoo,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.foos[0] = append(*s.foos[0], foo)

	return id
}

func (s *store_foo) ByID(id int) (foo Foo) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Foo",
				id,
			),
		)
	}

	return (*s.foos[*i])[k.index]
}

func (s *store_foo) All() FooAccessor {
	return FooAccessor{
		current:   0,
		ids:       s.ids,
		slicesFoo: s.foos,
	}
}

func (s *store_foo) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Foo",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_foo) deleteNative(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.foos[0])[k.index] = (*s.foos[0])[len((*s.foos[0]))-1]
	(*s.foos[0])[len(s.foos)-1] = zeroFoo
	*s.foos[0] = (*s.foos[0])[:len((*s.foos[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

var _ FooStore = (*store_foo)(nil)

// ///////////////////////////////////////
// ///////////////////////////////////////
// Bars
// ///////////////////////////////////////
// ///////////////////////////////////////
type BarResult struct {
	IDs  []int
	Bars []Bar
}

type BarAccessor struct {
	current   int
	ids       []*[]int
	slicesBar []*[]Bar
}

func (a *BarAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *BarAccessor) Bars() BarResult {
	return BarResult{
		IDs:  *a.ids[a.current],
		Bars: *a.slicesBar[a.current],
	}
}

type BarStore interface {
	Put(bar Bar) (id int)
	ByID(id int) (bar Bar)
	All() BarAccessor
	Delete(id int)
}

func newStore_Bar(keys *[]*entityKey, foobar *store_foobar) *store_bar {
	store := &store_bar{
		keys: keys,
		typeMap: []*int{
			nil,    // compositionIDFoo,
			new(0), // compositionIDBar,
			new(1), // compositiionIDFooBar
		},
	}

	store.delFns = []func(int){
		nil,
		store.deleteNative,
		foobar.deleteNative,
	}

	return store
}

type store_bar struct {
	keys    *[]*entityKey
	typeMap []*int
	delFns  []func(int)
	ids     []*[]int
	bars    []*[]Bar
}

func (s *store_bar) Put(bar Bar) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionIDBar,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.bars[0] = append(*s.bars[0], bar)

	return id
}

func (s *store_bar) ByID(id int) (bar Bar) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Bar",
				id,
			),
		)
	}

	return (*s.bars[*i])[k.index]
}

func (s *store_bar) All() BarAccessor {
	return BarAccessor{
		current:   0,
		ids:       s.ids,
		slicesBar: s.bars,
	}
}

func (s *store_bar) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Bar",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_bar) deleteNative(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.bars[0])[k.index] = (*s.bars[0])[len((*s.bars[0]))-1]
	(*s.bars[0])[len(s.bars)-1] = zeroFoo
	*s.bars[0] = (*s.bars[0])[:len((*s.bars[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

var _ BarStore = (*store_bar)(nil)

// ///////////////////////////////////////
// ///////////////////////////////////////
// FooBars
// ///////////////////////////////////////
// ///////////////////////////////////////
type FooBarResult struct {
	IDs  []int
	Foos []Foo
	Bars []Bar
}

type FooBarAccessor struct {
	current   int
	ids       []*[]int
	slicesFoo []*[]Foo
	slicesBar []*[]Bar
}

func (a *FooBarAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *FooBarAccessor) FooBars() FooBarResult {
	return FooBarResult{
		IDs:  *a.ids[a.current],
		Foos: *a.slicesFoo[a.current],
		Bars: *a.slicesBar[a.current],
	}
}

type FooBarStore interface {
	Put(foo Foo, bar Bar) (id int)
	ByID(id int) (foo Foo, bar Bar)
	All() FooBarAccessor
	Delete(id int)
}

func newStore_FooBar(keys *[]*entityKey) *store_foobar {
	store := &store_foobar{
		keys: keys,
		typeMap: []*int{
			nil,    // compositionIDFoo,
			nil,    // compositionIDBar,
			new(1), // compositiionIDFooBar
		},
	}

	store.delFns = []func(int){
		nil,
		nil,
		store.deleteNative,
	}

	return store
}

type store_foobar struct {
	keys    *[]*entityKey
	typeMap []*int
	delFns  []func(int)
	ids     []*[]int
	foos    []*[]Foo
	bars    []*[]Bar
}

func (s *store_foobar) Put(foo Foo, bar Bar) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionIDBar,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.foos[0] = append(*s.bars[0], bar)
	*s.bars[0] = append(*s.bars[0], bar)

	return id
}

func (s *store_foobar) ByID(id int) (foo Foo, bar Bar) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Bar",
				id,
			),
		)
	}

	return (*s.bars[*i])[k.index],
		(*s.foos[*i])[k.index]
}

func (s *store_foobar) All() FooBarAccessor {
	return FooBarAccessor{
		current:   0,
		ids:       s.ids,
		slicesFoo: s.foos,
		slicesBar: s.bars,
	}
}

func (s *store_foobar) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement FooBar",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_foobar) deleteNative(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.foos[0])[k.index] = (*s.foos[0])[len((*s.foos[0]))-1]
	(*s.foos[0])[len(s.foos)-1] = zeroFoo
	*s.foos[0] = (*s.foos[0])[:len((*s.foos[0]))-1]

	(*s.bars[0])[k.index] = (*s.bars[0])[len((*s.bars[0]))-1]
	(*s.bars[0])[len(s.bars)-1] = zeroFoo
	*s.bars[0] = (*s.bars[0])[:len((*s.bars[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

var _ FooBarStore = (*store_foobar)(nil)

// ///////////////////////////////////////
// ///////////////////////////////////////
// Store
// ///////////////////////////////////////
// ///////////////////////////////////////

type Store struct {
	idMap  []*entityKey
	Foo    FooStore
	Bar    BarStore
	FooBar FooBarStore
}

func NewStore() *Store {
	s := &Store{}

	foobar := newStore_FooBar(&s.idMap)
	foo := newStore_Foo(&s.idMap, foobar)
	bar := newStore_Bar(&s.idMap, foobar)

	s.FooBar = foobar
	s.Foo = foo
	s.Bar = bar

	return s
}
