// Code generated by fes v0.1.0-dev. DO NOT EDIT.
package entities

type compositionID uint64

const (
	compositionIDPositionable compositionID = iota
	compositionIDTravellable
	compositionIDTrader
	compositionIDShip
)

var (
	zeroPosition  Vector[float32]
	zeroDirection float64
	zeroVelocity  float64
	zeroIncome    int
	zeroGold      int
)

type entityKey struct {
	composition compositionID
	index       int
}

type storePositionable struct {
	ids       []int
	positions []Vector[float32]
}

type PositionableResult struct {
	IDs       []int
	Positions []Vector[float32]
}

type PositionableAccessor struct {
	current        int
	ids            [][]int
	slicesPosition [][]Vector[float32]
}

func (a *PositionableAccessor) Next() bool {
	if a.current < len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *PositionableAccessor) Positionables() PositionableResult {
	return PositionableResult{
		IDs:       a.ids[a.current],
		Positions: a.slicesPosition[a.current],
	}
}

type storeTravellable struct {
	ids        []int
	positions  []Vector[float32]
	directions []float64
	velocitys  []float64
}

type TravellableResult struct {
	IDs        []int
	Positions  []Vector[float32]
	Directions []float64
	Velocitys  []float64
}

type TravellableAccessor struct {
	current         int
	ids             [][]int
	slicesPosition  [][]Vector[float32]
	slicesDirection [][]float64
	slicesVelocity  [][]float64
}

func (a *TravellableAccessor) Next() bool {
	if a.current < len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *TravellableAccessor) Travellables() TravellableResult {
	return TravellableResult{
		IDs:        a.ids[a.current],
		Positions:  a.slicesPosition[a.current],
		Directions: a.slicesDirection[a.current],
		Velocitys:  a.slicesVelocity[a.current],
	}
}

type storeTrader struct {
	ids     []int
	incomes []int
	golds   []int
}

type TraderResult struct {
	IDs     []int
	Incomes []int
	Golds   []int
}

type TraderAccessor struct {
	current      int
	ids          [][]int
	slicesIncome [][]int
	slicesGold   [][]int
}

func (a *TraderAccessor) Next() bool {
	if a.current < len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *TraderAccessor) Traders() TraderResult {
	return TraderResult{
		IDs:     a.ids[a.current],
		Incomes: a.slicesIncome[a.current],
		Golds:   a.slicesGold[a.current],
	}
}

type storeShip struct {
	ids        []int
	positions  []Vector[float32]
	directions []float64
	velocitys  []float64
	incomes    []int
	golds      []int
}

type ShipResult struct {
	IDs        []int
	Positions  []Vector[float32]
	Directions []float64
	Velocitys  []float64
	Incomes    []int
	Golds      []int
}

type ShipAccessor struct {
	current         int
	ids             [][]int
	slicesPosition  [][]Vector[float32]
	slicesDirection [][]float64
	slicesVelocity  [][]float64
	slicesIncome    [][]int
	slicesGold      [][]int
}

func (a *ShipAccessor) Next() bool {
	if a.current < len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

func (a *ShipAccessor) Ships() ShipResult {
	return ShipResult{
		IDs:        a.ids[a.current],
		Positions:  a.slicesPosition[a.current],
		Directions: a.slicesDirection[a.current],
		Velocitys:  a.slicesVelocity[a.current],
		Incomes:    a.slicesIncome[a.current],
		Golds:      a.slicesGold[a.current],
	}
}

type Store struct {
	ids           []*entityKey
	positionables storePositionable
	travellables  storeTravellable
	traders       storeTrader
	ships         storeShip
}

var deleteFunctions = []func(store *Store, key entityKey){
	func(store *Store, key entityKey) {
		deleted := store.positionables.ids[key.index]

		store.positionables.ids[key.index] = store.positionables.ids[len(store.positionables.ids)-1]
		store.positionables.ids = store.positionables.ids[:len(store.positionables.ids)-1]

		store.positionables.positions[key.index] = store.positionables.positions[len(store.positionables.positions)-1]
		store.positionables.positions[len(store.positionables.positions)-1] = zeroPosition
		store.positionables.positions = store.positionables.positions[:len(store.positionables.positions)-1]

		store.ids[deleted] = nil
		store.ids[store.positionables.ids[key.index]].index = key.index
	},
	func(store *Store, key entityKey) {
		deleted := store.travellables.ids[key.index]

		store.travellables.ids[key.index] = store.travellables.ids[len(store.travellables.ids)-1]
		store.travellables.ids = store.travellables.ids[:len(store.travellables.ids)-1]

		store.travellables.positions[key.index] = store.travellables.positions[len(store.travellables.positions)-1]
		store.travellables.positions[len(store.travellables.positions)-1] = zeroPosition
		store.travellables.positions = store.travellables.positions[:len(store.travellables.positions)-1]

		store.travellables.directions[key.index] = store.travellables.directions[len(store.travellables.directions)-1]
		store.travellables.directions[len(store.travellables.directions)-1] = zeroDirection
		store.travellables.directions = store.travellables.directions[:len(store.travellables.directions)-1]

		store.travellables.velocitys[key.index] = store.travellables.velocitys[len(store.travellables.velocitys)-1]
		store.travellables.velocitys[len(store.travellables.velocitys)-1] = zeroVelocity
		store.travellables.velocitys = store.travellables.velocitys[:len(store.travellables.velocitys)-1]

		store.ids[deleted] = nil
		store.ids[store.travellables.ids[key.index]].index = key.index
	},
	func(store *Store, key entityKey) {
		deleted := store.traders.ids[key.index]

		store.traders.ids[key.index] = store.traders.ids[len(store.traders.ids)-1]
		store.traders.ids = store.traders.ids[:len(store.traders.ids)-1]

		store.traders.incomes[key.index] = store.traders.incomes[len(store.traders.incomes)-1]
		store.traders.incomes[len(store.traders.incomes)-1] = zeroIncome
		store.traders.incomes = store.traders.incomes[:len(store.traders.incomes)-1]

		store.traders.golds[key.index] = store.traders.golds[len(store.traders.golds)-1]
		store.traders.golds[len(store.traders.golds)-1] = zeroGold
		store.traders.golds = store.traders.golds[:len(store.traders.golds)-1]

		store.ids[deleted] = nil
		store.ids[store.traders.ids[key.index]].index = key.index
	},
	func(store *Store, key entityKey) {
		deleted := store.ships.ids[key.index]

		store.ships.ids[key.index] = store.ships.ids[len(store.ships.ids)-1]
		store.ships.ids = store.ships.ids[:len(store.ships.ids)-1]

		store.ships.positions[key.index] = store.ships.positions[len(store.ships.positions)-1]
		store.ships.positions[len(store.ships.positions)-1] = zeroPosition
		store.ships.positions = store.ships.positions[:len(store.ships.positions)-1]

		store.ships.directions[key.index] = store.ships.directions[len(store.ships.directions)-1]
		store.ships.directions[len(store.ships.directions)-1] = zeroDirection
		store.ships.directions = store.ships.directions[:len(store.ships.directions)-1]

		store.ships.velocitys[key.index] = store.ships.velocitys[len(store.ships.velocitys)-1]
		store.ships.velocitys[len(store.ships.velocitys)-1] = zeroVelocity
		store.ships.velocitys = store.ships.velocitys[:len(store.ships.velocitys)-1]

		store.ships.incomes[key.index] = store.ships.incomes[len(store.ships.incomes)-1]
		store.ships.incomes[len(store.ships.incomes)-1] = zeroIncome
		store.ships.incomes = store.ships.incomes[:len(store.ships.incomes)-1]

		store.ships.golds[key.index] = store.ships.golds[len(store.ships.golds)-1]
		store.ships.golds[len(store.ships.golds)-1] = zeroGold
		store.ships.golds = store.ships.golds[:len(store.ships.golds)-1]

		store.ids[deleted] = nil
		store.ids[store.ships.ids[key.index]].index = key.index
	},
}

func (s *Store) PositionableByID(id int) (
	position *Vector[float32],
) {
	key := s.ids[id]

	return &s.positionables.positions[key.index]
}

func (s *Store) Positionables() *PositionableAccessor {
	return &PositionableAccessor{
		current: 0,
		ids: [][]int{
			s.positionables.ids,
			s.travellables.ids,
			s.ships.ids,
		},
		slicesPosition: [][]Vector[float32]{
			s.positionables.positions,
			s.travellables.positions,
			s.ships.positions,
		},
	}
}

func (s *Store) PutPositionable(
	cPosition Vector[float32],
) int {
	id := len(s.ids)

	s.ids = append(s.ids, &entityKey{
		composition: compositionIDPositionable,
		index:       len(s.positionables.ids),
	})

	s.positionables.ids = append(s.positionables.ids, id)
	s.positionables.positions = append(
		s.positionables.positions,
		cPosition,
	)

	return id
}

func (s *Store) TravellableByID(id int) (
	position *Vector[float32],
	direction *float64,
	velocity *float64,
) {
	key := s.ids[id]

	return &s.travellables.positions[key.index],
		&s.travellables.directions[key.index],
		&s.travellables.velocitys[key.index]
}

func (s *Store) Travellables() *TravellableAccessor {
	return &TravellableAccessor{
		current: 0,
		ids: [][]int{
			s.travellables.ids,
			s.ships.ids,
		},
		slicesPosition: [][]Vector[float32]{
			s.travellables.positions,
			s.ships.positions,
		},
		slicesDirection: [][]float64{
			s.travellables.directions,
			s.ships.directions,
		},
		slicesVelocity: [][]float64{
			s.travellables.velocitys,
			s.ships.velocitys,
		},
	}
}

func (s *Store) PutTravellable(
	cPosition Vector[float32],
	cDirection float64,
	cVelocity float64,
) int {
	id := len(s.ids)

	s.ids = append(s.ids, &entityKey{
		composition: compositionIDTravellable,
		index:       len(s.travellables.ids),
	})

	s.travellables.ids = append(s.travellables.ids, id)
	s.travellables.positions = append(
		s.travellables.positions,
		cPosition,
	)
	s.travellables.directions = append(
		s.travellables.directions,
		cDirection,
	)
	s.travellables.velocitys = append(
		s.travellables.velocitys,
		cVelocity,
	)

	return id
}

func (s *Store) TraderByID(id int) (
	income *int,
	gold *int,
) {
	key := s.ids[id]

	return &s.traders.incomes[key.index],
		&s.traders.golds[key.index]
}

func (s *Store) Traders() *TraderAccessor {
	return &TraderAccessor{
		current: 0,
		ids: [][]int{
			s.traders.ids,
			s.ships.ids,
		},
		slicesIncome: [][]int{
			s.traders.incomes,
			s.ships.incomes,
		},
		slicesGold: [][]int{
			s.traders.golds,
			s.ships.golds,
		},
	}
}

func (s *Store) PutTrader(
	cIncome int,
	cGold int,
) int {
	id := len(s.ids)

	s.ids = append(s.ids, &entityKey{
		composition: compositionIDTrader,
		index:       len(s.traders.ids),
	})

	s.traders.ids = append(s.traders.ids, id)
	s.traders.incomes = append(
		s.traders.incomes,
		cIncome,
	)
	s.traders.golds = append(
		s.traders.golds,
		cGold,
	)

	return id
}

func (s *Store) ShipByID(id int) (
	position *Vector[float32],
	direction *float64,
	velocity *float64,
	income *int,
	gold *int,
) {
	key := s.ids[id]

	return &s.ships.positions[key.index],
		&s.ships.directions[key.index],
		&s.ships.velocitys[key.index],
		&s.ships.incomes[key.index],
		&s.ships.golds[key.index]
}

func (s *Store) Ships() *ShipAccessor {
	return &ShipAccessor{
		current: 0,
		ids: [][]int{
			s.ships.ids,
		},
		slicesPosition: [][]Vector[float32]{
			s.ships.positions,
		},
		slicesDirection: [][]float64{
			s.ships.directions,
		},
		slicesVelocity: [][]float64{
			s.ships.velocitys,
		},
		slicesIncome: [][]int{
			s.ships.incomes,
		},
		slicesGold: [][]int{
			s.ships.golds,
		},
	}
}

func (s *Store) PutShip(
	cPosition Vector[float32],
	cDirection float64,
	cVelocity float64,
	cIncome int,
	cGold int,
) int {
	id := len(s.ids)

	s.ids = append(s.ids, &entityKey{
		composition: compositionIDShip,
		index:       len(s.ships.ids),
	})

	s.ships.ids = append(s.ships.ids, id)
	s.ships.positions = append(
		s.ships.positions,
		cPosition,
	)
	s.ships.directions = append(
		s.ships.directions,
		cDirection,
	)
	s.ships.velocitys = append(
		s.ships.velocitys,
		cVelocity,
	)
	s.ships.incomes = append(
		s.ships.incomes,
		cIncome,
	)
	s.ships.golds = append(
		s.ships.golds,
		cGold,
	)

	return id
}

func Delete(store *Store, id int) {
	key := store.ids[id]

	deleteFunctions[key.composition](store, *key)
}
