// Code generated by fes v0.0.0-20260424172520-34e5b561c0d3. DO NOT EDIT.
package entities

import "fmt"

type compositionID uint64

const (
	compositionID_Ship compositionID = iota
	compositionID_Travellable
	compositionID_Positionable
	compositionID_Trader
)

var (
	zero_position  Vector[float32]
	zero_direction float64
	zero_velocity  float64
	zero_income    int
	zero_gold      int
)

type entityKey struct {
	composition compositionID
	index       int
}

// ShipResult provides access to a batch of Ship whereby each index
// across all the underlying slices represents a single entity/instance (i.e.
// index 0 of each slice represents that specific component of the entity).
//
// To update the underlying entity, you can update the values of the enclosed
// slices directly, but appending to the slices will not persist new entities
// to the store.
type ShipResult struct {
	IDs        []int
	positions  []Vector[float32]
	directions []float64
	velocitys  []float64
	incomes    []int
	golds      []int
}

// ShipAccessor provides access to all entities that implement Ship,
// either canonically or otherwise. It provides access via the slices in which
// they are stored, and the batches must be iterated through via Next().
type ShipAccessor struct {
	current         int
	ids             []*[]int
	cpnt_positions  []*[]Vector[float32]
	cpnt_directions []*[]float64
	cpnt_velocitys  []*[]float64
	cpnt_incomes    []*[]int
	cpnt_golds      []*[]int
}

// Next progresses the ShipAccessor on to the next batch of Ships (to
// be subsequently retrieved via Ships), unless false is returned, in which
// there are no more batches and all Ships have been exhausted.
func (a *ShipAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

// Ships returns a batch (grouped by underlying composition) of Ships
// in the form of ShipResult. The underlying Ship instances can be
// accessed by querying the same index across all enclosed component slices,
// i.e. the values within each slice at index 0 make up a single entity, the
// same for index 1 and so forth.
func (a *ShipAccessor) Ships() ShipResult {
	return ShipResult{
		IDs:        *a.ids[a.current],
		positions:  *a.cpnt_positions[a.current],
		directions: *a.cpnt_directions[a.current],
		velocitys:  *a.cpnt_velocitys[a.current],
		incomes:    *a.cpnt_incomes[a.current],
		golds:      *a.cpnt_golds[a.current],
	}
}

// ShipStore provides access to Ship instances, whether canonical
// (implementing Ship directly), or other compositions that happen to
// implement Ship.
//
// All Ship instances registered to the main Store can be accessed through
// ShipStore.
type ShipStore interface {
	// Put stores an instance (entity) of Ship in Store and returns its ID.
	Put(
		position Vector[float32],
		direction float64,
		velocity float64,
		income int,
		gold int,
	) (id int)

	// ByID returns the instance of Ship with the provided ID. If the ID
	// pertains to a non-canonical instance of Ship, it will still return
	// the Ship fields of said instance.
	ByID(id int) (
		position *Vector[float32],
		direction *float64,
		velocity *float64,
		income *int,
		gold *int,
	)

	// All returns a ShipAccessor that provides access to all Ship
	// instances (canonical or otherwise). This should be used to perform
	// composition-based actions to many instances.
	All() ShipAccessor

	// Delete deletes the Ship instance of the provided ID. If the
	// requested instance is not canonical (i.e. implements Ship but is of
	// another composition), then it will still be deleted as though a deletion
	// of the other type of composition was requested.
	Delete(id int)
}

type store_Ship struct {
	keys            *[]*entityKey
	typeMap         []*int
	delFns          []func(int)
	ids             []*[]int
	cpnt_positions  []*[]Vector[float32]
	cpnt_directions []*[]float64
	cpnt_velocitys  []*[]float64
	cpnt_incomes    []*[]int
	cpnt_golds      []*[]int
}

func (s *store_Ship) Put(
	cpnt_position Vector[float32],
	cpnt_direction float64,
	cpnt_velocity float64,
	cpnt_income int,
	cpnt_gold int,
) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionID_Ship,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.cpnt_positions[0] = append(*s.cpnt_positions[0], cpnt_position)
	*s.cpnt_directions[0] = append(*s.cpnt_directions[0], cpnt_direction)
	*s.cpnt_velocitys[0] = append(*s.cpnt_velocitys[0], cpnt_velocity)
	*s.cpnt_incomes[0] = append(*s.cpnt_incomes[0], cpnt_income)
	*s.cpnt_golds[0] = append(*s.cpnt_golds[0], cpnt_gold)

	return id
}

func (s *store_Ship) ByID(id int) (
	cpnt_position *Vector[float32],
	cpnt_direction *float64,
	cpnt_velocity *float64,
	cpnt_income *int,
	cpnt_gold *int,
) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Ship",
				id,
			),
		)
	}

	return &(*s.cpnt_positions[*i])[k.index],
		&(*s.cpnt_directions[*i])[k.index],
		&(*s.cpnt_velocitys[*i])[k.index],
		&(*s.cpnt_incomes[*i])[k.index],
		&(*s.cpnt_golds[*i])[k.index]
}

func (s *store_Ship) All() ShipAccessor {
	return ShipAccessor{
		current: 0,
		ids:     s.ids,

		cpnt_positions:  s.cpnt_positions,
		cpnt_directions: s.cpnt_directions,
		cpnt_velocitys:  s.cpnt_velocitys,
		cpnt_incomes:    s.cpnt_incomes,
		cpnt_golds:      s.cpnt_golds,
	}
}

func (s *store_Ship) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Ship",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_Ship) deleteCanonical(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.cpnt_positions[0])[k.index] = (*s.cpnt_positions[0])[len((*s.cpnt_positions[0]))-1]
	(*s.cpnt_positions[0])[len(s.cpnt_positions)-1] = zero_position
	*s.cpnt_positions[0] = (*s.cpnt_positions[0])[:len((*s.cpnt_positions[0]))-1]

	(*s.cpnt_directions[0])[k.index] = (*s.cpnt_directions[0])[len((*s.cpnt_directions[0]))-1]
	(*s.cpnt_directions[0])[len(s.cpnt_directions)-1] = zero_direction
	*s.cpnt_directions[0] = (*s.cpnt_directions[0])[:len((*s.cpnt_directions[0]))-1]

	(*s.cpnt_velocitys[0])[k.index] = (*s.cpnt_velocitys[0])[len((*s.cpnt_velocitys[0]))-1]
	(*s.cpnt_velocitys[0])[len(s.cpnt_velocitys)-1] = zero_velocity
	*s.cpnt_velocitys[0] = (*s.cpnt_velocitys[0])[:len((*s.cpnt_velocitys[0]))-1]

	(*s.cpnt_incomes[0])[k.index] = (*s.cpnt_incomes[0])[len((*s.cpnt_incomes[0]))-1]
	(*s.cpnt_incomes[0])[len(s.cpnt_incomes)-1] = zero_income
	*s.cpnt_incomes[0] = (*s.cpnt_incomes[0])[:len((*s.cpnt_incomes[0]))-1]

	(*s.cpnt_golds[0])[k.index] = (*s.cpnt_golds[0])[len((*s.cpnt_golds[0]))-1]
	(*s.cpnt_golds[0])[len(s.cpnt_golds)-1] = zero_gold
	*s.cpnt_golds[0] = (*s.cpnt_golds[0])[:len((*s.cpnt_golds[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

func newStore_Ship(
	keys *[]*entityKey,
) *store_Ship {
	store := &store_Ship{
		keys: keys,
		typeMap: []*int{
			nil,
			nil,
			nil,
			new(0),
		},
		ids: []*[]int{
			new([]int),
		},

		cpnt_positions: []*[]Vector[float32]{
			new([]Vector[float32]),
		},

		cpnt_directions: []*[]float64{
			new([]float64),
		},

		cpnt_velocitys: []*[]float64{
			new([]float64),
		},

		cpnt_incomes: []*[]int{
			new([]int),
		},

		cpnt_golds: []*[]int{
			new([]int),
		},
	}

	store.delFns = []func(int){
		store.deleteCanonical,
	}

	return store
}

// TravellableResult provides access to a batch of Travellable whereby each index
// across all the underlying slices represents a single entity/instance (i.e.
// index 0 of each slice represents that specific component of the entity).
//
// To update the underlying entity, you can update the values of the enclosed
// slices directly, but appending to the slices will not persist new entities
// to the store.
type TravellableResult struct {
	IDs        []int
	positions  []Vector[float32]
	directions []float64
	velocitys  []float64
}

// TravellableAccessor provides access to all entities that implement Travellable,
// either canonically or otherwise. It provides access via the slices in which
// they are stored, and the batches must be iterated through via Next().
type TravellableAccessor struct {
	current         int
	ids             []*[]int
	cpnt_positions  []*[]Vector[float32]
	cpnt_directions []*[]float64
	cpnt_velocitys  []*[]float64
}

// Next progresses the TravellableAccessor on to the next batch of Travellables (to
// be subsequently retrieved via Travellables), unless false is returned, in which
// there are no more batches and all Travellables have been exhausted.
func (a *TravellableAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

// Travellables returns a batch (grouped by underlying composition) of Travellables
// in the form of TravellableResult. The underlying Travellable instances can be
// accessed by querying the same index across all enclosed component slices,
// i.e. the values within each slice at index 0 make up a single entity, the
// same for index 1 and so forth.
func (a *TravellableAccessor) Travellables() TravellableResult {
	return TravellableResult{
		IDs:        *a.ids[a.current],
		positions:  *a.cpnt_positions[a.current],
		directions: *a.cpnt_directions[a.current],
		velocitys:  *a.cpnt_velocitys[a.current],
	}
}

// TravellableStore provides access to Travellable instances, whether canonical
// (implementing Travellable directly), or other compositions that happen to
// implement Travellable.
//
// All Travellable instances registered to the main Store can be accessed through
// TravellableStore.
type TravellableStore interface {
	// Put stores an instance (entity) of Travellable in Store and returns its ID.
	Put(
		position Vector[float32],
		direction float64,
		velocity float64,
	) (id int)

	// ByID returns the instance of Travellable with the provided ID. If the ID
	// pertains to a non-canonical instance of Travellable, it will still return
	// the Travellable fields of said instance.
	ByID(id int) (
		position *Vector[float32],
		direction *float64,
		velocity *float64,
	)

	// All returns a TravellableAccessor that provides access to all Travellable
	// instances (canonical or otherwise). This should be used to perform
	// composition-based actions to many instances.
	All() TravellableAccessor

	// Delete deletes the Travellable instance of the provided ID. If the
	// requested instance is not canonical (i.e. implements Travellable but is of
	// another composition), then it will still be deleted as though a deletion
	// of the other type of composition was requested.
	Delete(id int)
}

type store_Travellable struct {
	keys            *[]*entityKey
	typeMap         []*int
	delFns          []func(int)
	ids             []*[]int
	cpnt_positions  []*[]Vector[float32]
	cpnt_directions []*[]float64
	cpnt_velocitys  []*[]float64
}

func (s *store_Travellable) Put(
	cpnt_position Vector[float32],
	cpnt_direction float64,
	cpnt_velocity float64,
) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionID_Travellable,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.cpnt_positions[0] = append(*s.cpnt_positions[0], cpnt_position)
	*s.cpnt_directions[0] = append(*s.cpnt_directions[0], cpnt_direction)
	*s.cpnt_velocitys[0] = append(*s.cpnt_velocitys[0], cpnt_velocity)

	return id
}

func (s *store_Travellable) ByID(id int) (
	cpnt_position *Vector[float32],
	cpnt_direction *float64,
	cpnt_velocity *float64,
) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Travellable",
				id,
			),
		)
	}

	return &(*s.cpnt_positions[*i])[k.index],
		&(*s.cpnt_directions[*i])[k.index],
		&(*s.cpnt_velocitys[*i])[k.index]
}

func (s *store_Travellable) All() TravellableAccessor {
	return TravellableAccessor{
		current: 0,
		ids:     s.ids,

		cpnt_positions:  s.cpnt_positions,
		cpnt_directions: s.cpnt_directions,
		cpnt_velocitys:  s.cpnt_velocitys,
	}
}

func (s *store_Travellable) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Travellable",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_Travellable) deleteCanonical(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.cpnt_positions[0])[k.index] = (*s.cpnt_positions[0])[len((*s.cpnt_positions[0]))-1]
	(*s.cpnt_positions[0])[len(s.cpnt_positions)-1] = zero_position
	*s.cpnt_positions[0] = (*s.cpnt_positions[0])[:len((*s.cpnt_positions[0]))-1]

	(*s.cpnt_directions[0])[k.index] = (*s.cpnt_directions[0])[len((*s.cpnt_directions[0]))-1]
	(*s.cpnt_directions[0])[len(s.cpnt_directions)-1] = zero_direction
	*s.cpnt_directions[0] = (*s.cpnt_directions[0])[:len((*s.cpnt_directions[0]))-1]

	(*s.cpnt_velocitys[0])[k.index] = (*s.cpnt_velocitys[0])[len((*s.cpnt_velocitys[0]))-1]
	(*s.cpnt_velocitys[0])[len(s.cpnt_velocitys)-1] = zero_velocity
	*s.cpnt_velocitys[0] = (*s.cpnt_velocitys[0])[:len((*s.cpnt_velocitys[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

func newStore_Travellable(
	keys *[]*entityKey,
	Ship *store_Ship,
) *store_Travellable {
	store := &store_Travellable{
		keys: keys,
		typeMap: []*int{
			new(1),

			new(0),
			nil,
			nil,
		},
		ids: []*[]int{
			new([]int),
			Ship.ids[0],
		},

		cpnt_positions: []*[]Vector[float32]{
			new([]Vector[float32]),
			Ship.cpnt_positions[0],
		},

		cpnt_directions: []*[]float64{
			new([]float64),
			Ship.cpnt_directions[0],
		},

		cpnt_velocitys: []*[]float64{
			new([]float64),
			Ship.cpnt_velocitys[0],
		},
	}

	store.delFns = []func(int){
		store.deleteCanonical,
		Ship.deleteCanonical,
	}

	return store
}

// PositionableResult provides access to a batch of Positionable whereby each index
// across all the underlying slices represents a single entity/instance (i.e.
// index 0 of each slice represents that specific component of the entity).
//
// To update the underlying entity, you can update the values of the enclosed
// slices directly, but appending to the slices will not persist new entities
// to the store.
type PositionableResult struct {
	IDs       []int
	positions []Vector[float32]
}

// PositionableAccessor provides access to all entities that implement Positionable,
// either canonically or otherwise. It provides access via the slices in which
// they are stored, and the batches must be iterated through via Next().
type PositionableAccessor struct {
	current        int
	ids            []*[]int
	cpnt_positions []*[]Vector[float32]
}

// Next progresses the PositionableAccessor on to the next batch of Positionables (to
// be subsequently retrieved via Positionables), unless false is returned, in which
// there are no more batches and all Positionables have been exhausted.
func (a *PositionableAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

// Positionables returns a batch (grouped by underlying composition) of Positionables
// in the form of PositionableResult. The underlying Positionable instances can be
// accessed by querying the same index across all enclosed component slices,
// i.e. the values within each slice at index 0 make up a single entity, the
// same for index 1 and so forth.
func (a *PositionableAccessor) Positionables() PositionableResult {
	return PositionableResult{
		IDs:       *a.ids[a.current],
		positions: *a.cpnt_positions[a.current],
	}
}

// PositionableStore provides access to Positionable instances, whether canonical
// (implementing Positionable directly), or other compositions that happen to
// implement Positionable.
//
// All Positionable instances registered to the main Store can be accessed through
// PositionableStore.
type PositionableStore interface {
	// Put stores an instance (entity) of Positionable in Store and returns its ID.
	Put(
		position Vector[float32],
	) (id int)

	// ByID returns the instance of Positionable with the provided ID. If the ID
	// pertains to a non-canonical instance of Positionable, it will still return
	// the Positionable fields of said instance.
	ByID(id int) (
		position *Vector[float32],
	)

	// All returns a PositionableAccessor that provides access to all Positionable
	// instances (canonical or otherwise). This should be used to perform
	// composition-based actions to many instances.
	All() PositionableAccessor

	// Delete deletes the Positionable instance of the provided ID. If the
	// requested instance is not canonical (i.e. implements Positionable but is of
	// another composition), then it will still be deleted as though a deletion
	// of the other type of composition was requested.
	Delete(id int)
}

type store_Positionable struct {
	keys           *[]*entityKey
	typeMap        []*int
	delFns         []func(int)
	ids            []*[]int
	cpnt_positions []*[]Vector[float32]
}

func (s *store_Positionable) Put(
	cpnt_position Vector[float32],
) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionID_Positionable,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.cpnt_positions[0] = append(*s.cpnt_positions[0], cpnt_position)

	return id
}

func (s *store_Positionable) ByID(id int) (
	cpnt_position *Vector[float32],
) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Positionable",
				id,
			),
		)
	}

	return &(*s.cpnt_positions[*i])[k.index]
}

func (s *store_Positionable) All() PositionableAccessor {
	return PositionableAccessor{
		current: 0,
		ids:     s.ids,

		cpnt_positions: s.cpnt_positions,
	}
}

func (s *store_Positionable) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Positionable",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_Positionable) deleteCanonical(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.cpnt_positions[0])[k.index] = (*s.cpnt_positions[0])[len((*s.cpnt_positions[0]))-1]
	(*s.cpnt_positions[0])[len(s.cpnt_positions)-1] = zero_position
	*s.cpnt_positions[0] = (*s.cpnt_positions[0])[:len((*s.cpnt_positions[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

func newStore_Positionable(
	keys *[]*entityKey,
	Ship *store_Ship,
	Travellable *store_Travellable,
) *store_Positionable {
	store := &store_Positionable{
		keys: keys,
		typeMap: []*int{
			new(0),
			new(1),

			nil,
			nil,
		},
		ids: []*[]int{
			new([]int),
			Ship.ids[0],
			Travellable.ids[0],
		},

		cpnt_positions: []*[]Vector[float32]{
			new([]Vector[float32]),
			Ship.cpnt_positions[0],
			Travellable.cpnt_positions[0],
		},
	}

	store.delFns = []func(int){
		store.deleteCanonical,
		Ship.deleteCanonical,
		Travellable.deleteCanonical,
	}

	return store
}

// TraderResult provides access to a batch of Trader whereby each index
// across all the underlying slices represents a single entity/instance (i.e.
// index 0 of each slice represents that specific component of the entity).
//
// To update the underlying entity, you can update the values of the enclosed
// slices directly, but appending to the slices will not persist new entities
// to the store.
type TraderResult struct {
	IDs     []int
	incomes []int
	golds   []int
}

// TraderAccessor provides access to all entities that implement Trader,
// either canonically or otherwise. It provides access via the slices in which
// they are stored, and the batches must be iterated through via Next().
type TraderAccessor struct {
	current      int
	ids          []*[]int
	cpnt_incomes []*[]int
	cpnt_golds   []*[]int
}

// Next progresses the TraderAccessor on to the next batch of Traders (to
// be subsequently retrieved via Traders), unless false is returned, in which
// there are no more batches and all Traders have been exhausted.
func (a *TraderAccessor) Next() bool {
	if a.current == len(a.ids)-1 {
		return false
	}

	a.current++

	return true
}

// Traders returns a batch (grouped by underlying composition) of Traders
// in the form of TraderResult. The underlying Trader instances can be
// accessed by querying the same index across all enclosed component slices,
// i.e. the values within each slice at index 0 make up a single entity, the
// same for index 1 and so forth.
func (a *TraderAccessor) Traders() TraderResult {
	return TraderResult{
		IDs:     *a.ids[a.current],
		incomes: *a.cpnt_incomes[a.current],
		golds:   *a.cpnt_golds[a.current],
	}
}

// TraderStore provides access to Trader instances, whether canonical
// (implementing Trader directly), or other compositions that happen to
// implement Trader.
//
// All Trader instances registered to the main Store can be accessed through
// TraderStore.
type TraderStore interface {
	// Put stores an instance (entity) of Trader in Store and returns its ID.
	Put(
		income int,
		gold int,
	) (id int)

	// ByID returns the instance of Trader with the provided ID. If the ID
	// pertains to a non-canonical instance of Trader, it will still return
	// the Trader fields of said instance.
	ByID(id int) (
		income *int,
		gold *int,
	)

	// All returns a TraderAccessor that provides access to all Trader
	// instances (canonical or otherwise). This should be used to perform
	// composition-based actions to many instances.
	All() TraderAccessor

	// Delete deletes the Trader instance of the provided ID. If the
	// requested instance is not canonical (i.e. implements Trader but is of
	// another composition), then it will still be deleted as though a deletion
	// of the other type of composition was requested.
	Delete(id int)
}

type store_Trader struct {
	keys         *[]*entityKey
	typeMap      []*int
	delFns       []func(int)
	ids          []*[]int
	cpnt_incomes []*[]int
	cpnt_golds   []*[]int
}

func (s *store_Trader) Put(
	cpnt_income int,
	cpnt_gold int,
) (id int) {
	id = len(*s.keys)

	*s.keys = append(
		*s.keys,
		&entityKey{
			composition: compositionID_Trader,
			index:       len(*s.ids[0]),
		},
	)

	*s.ids[0] = append(*s.ids[0], id)
	*s.cpnt_incomes[0] = append(*s.cpnt_incomes[0], cpnt_income)
	*s.cpnt_golds[0] = append(*s.cpnt_golds[0], cpnt_gold)

	return id
}

func (s *store_Trader) ByID(id int) (
	cpnt_income *int,
	cpnt_gold *int,
) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Trader",
				id,
			),
		)
	}

	return &(*s.cpnt_incomes[*i])[k.index],
		&(*s.cpnt_golds[*i])[k.index]
}

func (s *store_Trader) All() TraderAccessor {
	return TraderAccessor{
		current: 0,
		ids:     s.ids,

		cpnt_incomes: s.cpnt_incomes,
		cpnt_golds:   s.cpnt_golds,
	}
}

func (s *store_Trader) Delete(id int) {
	k := (*s.keys)[id]

	i := s.typeMap[k.composition]
	if i == nil {
		panic(
			fmt.Errorf(
				"entity of provided ID does not implement Trader",
				id,
			),
		)
	}

	s.delFns[*i](id)
}

func (s *store_Trader) deleteCanonical(id int) {
	k := (*s.keys)[id]

	(*s.ids[0]) = (*s.ids[len((*s.ids[0]))-1])
	*s.ids[0] = (*s.ids[0])[:len(*s.ids[0])-1]

	(*s.cpnt_incomes[0])[k.index] = (*s.cpnt_incomes[0])[len((*s.cpnt_incomes[0]))-1]
	(*s.cpnt_incomes[0])[len(s.cpnt_incomes)-1] = zero_income
	*s.cpnt_incomes[0] = (*s.cpnt_incomes[0])[:len((*s.cpnt_incomes[0]))-1]

	(*s.cpnt_golds[0])[k.index] = (*s.cpnt_golds[0])[len((*s.cpnt_golds[0]))-1]
	(*s.cpnt_golds[0])[len(s.cpnt_golds)-1] = zero_gold
	*s.cpnt_golds[0] = (*s.cpnt_golds[0])[:len((*s.cpnt_golds[0]))-1]

	(*s.keys)[id] = nil
	(*s.keys)[(*s.ids[0])[k.index]].index = k.index
}

func newStore_Trader(
	keys *[]*entityKey,
	Ship *store_Ship,
) *store_Trader {
	store := &store_Trader{
		keys: keys,
		typeMap: []*int{
			new(1),

			nil,
			new(0),
			nil,
		},
		ids: []*[]int{
			new([]int),
			Ship.ids[0],
		},

		cpnt_incomes: []*[]int{
			new([]int),
			Ship.cpnt_incomes[0],
		},

		cpnt_golds: []*[]int{
			new([]int),
			Ship.cpnt_golds[0],
		},
	}

	store.delFns = []func(int){
		store.deleteCanonical,
		Ship.deleteCanonical,
	}

	return store
}

// Store is the main storage component for all configured compositions,
// providing namespaced access to each type of composition through its fields.
//
// A Store instance can be created via NewStore.
type Store interface {
	Ship() ShipStore
	Travellable() TravellableStore
	Positionable() PositionableStore
	Trader() TraderStore
}

type store struct {
	idMap         []*entityKey
	_Ship         *store_Ship
	_Travellable  *store_Travellable
	_Positionable *store_Positionable
	_Trader       *store_Trader
}

func (s *store) Ship() ShipStore {
	return s._Ship
}

func (s *store) Travellable() TravellableStore {
	return s._Travellable
}

func (s *store) Positionable() PositionableStore {
	return s._Positionable
}

func (s *store) Trader() TraderStore {
	return s._Trader
}

// NewStore returns a ready-to-use Store instance.
func NewStore() Store {
	s := &store{}

	s._Ship = newStore_Ship(
		&s.idMap,
	)

	s._Travellable = newStore_Travellable(
		&s.idMap,
		s._Ship,
	)

	s._Positionable = newStore_Positionable(
		&s.idMap,
		s._Ship,
		s._Travellable,
	)

	s._Trader = newStore_Trader(
		&s.idMap,
		s._Ship,
	)

	return s
}
